apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp-deployment
spec:
  selector:
    app: webapp-deployment
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
