apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-virtual
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        exact: /time
    route:
    - destination:
        host: webappp
        port:
          number: 8080
  - match:
    - uri:
        exact: /statistics
    route:
    - destination:
        host: webapp
        port:
          number: 8080